export default {
    type: 'select',
    title: 'Select a template:',
    key: 'template',
    items: [
        { label: 'Default (All Sources)', value: 'default' },
        { label: 'Basic Bot Setup', value: 'basic-bot' },
        { label: 'Music Bot (with plugins)', value: 'music-bot' },
        { label: '─── SINGLE SOURCE TEMPLATES ───', value: 'custom', disabled: true },
        { label: 'YouTube Only', value: 'youtube-only' },
        { label: 'SoundCloud Only', value: 'soundcloud-only' },
        { label: 'Twitch Only', value: 'twitch-only' },
        { label: 'Vimeo Only', value: 'vimeo-only' },
        { label: 'Bandcamp Only', value: 'bandcamp-only' },
        { label: 'HTTP Streaming Only', value: 'http-only' },
        { label: 'Local Files Only', value: 'local-only' },
        { label: 'Spotify Only (Requires Plugin/Auth)', value: 'spotify-only' },
        { label: 'Apple Music Only (Requires Plugin)', value: 'applemusic-only' },
        { label: 'Deezer Only (Requires Plugin/Auth)', value: 'deezer-only' },
        { label: '─── OPTIMIZED TEMPLATES ───', value: 'custom2', disabled: true },
        { label: 'High Performance (Max Buffers)', value: 'high-performance' },
        { label: 'Low Memory (Strict Limits)', value: 'low-memory' },
        { label: 'Secure Private (Localhost Bind)', value: 'secure-private' },
        { label: 'Podcast & Radio (Long Buffer)', value: 'podcast-radio' },
        { label: 'Minimal (No Plugins)', value: 'minimal-all-sources' },
        { label: '───────────────────────────────', value: 'custom3', disabled: true },
        { label: 'Custom (from templates/)', value: 'custom' },
    ],
};
